Fixed typo - "Stay focus"
zidoro/pomatez pull request #597
Opened 2024-01-18 20:42 UTC by ZelnickB

In several locations, the app uses the phrase "Stay focus," which should say "Stay focused" (grammatical error). The commit in this pull request resolves the issue.

For clarity, the names of variables and functions that use the words "stay" and "focus" have also been updated.

2024-01-23 00:10 UTC, sekwah41 approved these changes

2024-03-12 01:33 UTC, ZelnickB commented
@sekwah41 Done.

2024-03-13 06:43 UTC, sekwah41 approved these changes
Looks good, will test it tonight!

2024-03-15 05:42 UTC, sekwah41 requested changes

2024-03-15 05:42 UTC, sekwah41 commented on app/renderer/src/contexts/CounterContext.tsx
> -  const [count, setCount] = useState(config.stayFocus * 60);
You can change the litteral translations but can you revert the variables. The issue is that these are stored as a json so it means the settings don't work/exist and result in an NAN for existing users
![image](https://github.com/zidoro/pomatez/assets/3209834/47d87327-38bd-4069-8bdb-741cab556295)

2024-03-15 05:43 UTC, sekwah41 commented on app/renderer/src/contexts/CounterContext.tsx
> -  const [count, setCount] = useState(config.stayFocus * 60);
![image](https://github.com/zidoro/pomatez/assets/3209834/85d89e7e-b02d-4cae-9549-0355417d83fd)

2024-03-15 05:44 UTC, sekwah41 commented
To change the stay-focused variable itself, we'd need to load it from both the old naming and the new naming to allow it to transition users over slowly. While its an option its a small price to pay for a value users will never see.

2024-03-19 02:52 UTC, ZelnickB commented
@sekwah41 Fixed.

2024-04-02 18:32 UTC, sekwah41 commented
Sorry for the delay, ill take a look at this tomorrow ^.^

2024-04-06 02:28 UTC, sekwah41 approved these changes

2024-04-06 02:29 UTC, merged