refactor(store): finish migration to redux-toolkit
zidoro/pomatez pull request #599
Opened 2024-01-27 19:15 UTC by dubisdev

This PR continues #594 

The Tasks store has been migrated to RTK and now all the codebase is using RTK.

2024-01-27 22:20 UTC, sekwah41 requested changes
Left a response on discord. Seems to be a strange issue with skipping tasks on the timer window with this pr or the previous one

2024-01-28 09:15 UTC, dubisdev commented on app/renderer/src/store/tasks/index.ts
> +          ...notDoneCards.splice(0, 1),
Here is the error

splice returns the deleted one and not the rest of the Tasks

2024-01-28 12:48 UTC, dubisdev commented
I think the problem is solved now :)

2024-01-28 18:03 UTC, sekwah41 commented
Looks all good :D

2024-01-28 18:03 UTC, sekwah41 approved these changes

2024-01-28 18:03 UTC, merged